In [ ]:
# MIT License
#
# Copyright (c) 2020 Fagner Cunha
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# Redes Neurais Completamente Conectadas com TensorFlow

<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/alcunha/nn-with-tf/blob/master/Fully-Connected-Neural-Networks-with-TF.ipynb"><img src="./images/colab_logo_32px.png" />Executar no Google Colab</a>
  </td>
  <td>
    <a href="https://github.com/alcunha/nn-with-tf/blob/master/Fully-Connected-Neural-Networks-with-TF.ipynb"><img src="./images/GitHub-Mark-32px.png" />Ver código no GitHub</a>
  </td>
</table>

In [ ]:
! pip install tensorflow pandas

In [1]:
import tensorflow as tf
import pandas as pd

from tensorflow import keras

## Tensores

Tensores são arrays multi-dimensionais com um mesmo tipo (**dtype**).

#### Rank 0 ("Escalar")

In [2]:
a = tf.constant(4)
b = tf.constant(3.2)
c = tf.constant('casa')

In [3]:
print(a)
print(b)
print(c)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(3.2, shape=(), dtype=float32)
tf.Tensor(b'casa', shape=(), dtype=string)


#### Rank 1 ("Vetor")

In [4]:
list1 = tf.constant([4, 3])
list2 = tf.constant([3.2, 2])
list3 = tf.constant(['casa', 'rua'])

In [5]:
print(list1)
print(list2)
print(list3)

tf.Tensor([4 3], shape=(2,), dtype=int32)
tf.Tensor([3.2 2. ], shape=(2,), dtype=float32)
tf.Tensor([b'casa' b'rua'], shape=(2,), dtype=string)


Lista com tipos diferentes vai gerar erro:

In [6]:
#list4 = tf.constant(['casa', 4])

#### Rank 2 ("Matriz")

In [7]:
mat1 = tf.constant([[2, 3],
                    [4, 5]])
mat2 = tf.constant([[1, 1],
                    [1, 1.]])

In [8]:
print(mat1)
print(mat2)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


Convertendo os valores de um tensor para o NumPy:

In [9]:
mat1.numpy()

array([[2, 3],
       [4, 5]], dtype=int32)

In [10]:
zeros = tf.zeros([2, 3], dtype=tf.int32)
print(zeros)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [11]:
ones = tf.ones([3, 3, 2], dtype=tf.float32)
print(ones)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(3, 3, 2), dtype=float32)


### Operações

In [12]:
a = tf.cast(a, tf.float32)

In [13]:
a + b

<tf.Tensor: shape=(), dtype=float32, numpy=7.2>

In [14]:
tf.add(a, b)

<tf.Tensor: shape=(), dtype=float32, numpy=7.2>

In [15]:
print(list1)
print(list1.shape)
print(list1.dtype)
print(list1 + tf.ones(list1.shape, dtype=list1.dtype))

tf.Tensor([4 3], shape=(2,), dtype=int32)
(2,)
<dtype: 'int32'>
tf.Tensor([5 4], shape=(2,), dtype=int32)


Multiplicação de matrizes

In [16]:
mat1 = tf.constant([[1, 2, 3],
                   [4, 5, 6]])

mat2 = tf.constant([
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4],
])

In [17]:
print(mat1.shape)
print(mat2.shape)

(2, 3)
(3, 4)


In [18]:
tf.matmul(mat1, mat2)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 6, 12, 18, 24],
       [15, 30, 45, 60]], dtype=int32)>

In [19]:
mat1 * mat1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

#### Bônus: Números complexos

In [20]:
tf.complex(a, b)

<tf.Tensor: shape=(), dtype=complex64, numpy=(4+3.2j)>